<a href="https://colab.research.google.com/github/jasonstoy/TensorFlow/blob/main/1.Create%20a%20Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [3]:
# cmd + shift + space: check Fn

In [4]:
# Create tensors with tf.constant
scalar = tf.constant(1) 
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [6]:
# Creat a vector
vector = tf.constant([1,1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# Create another matrix with specified data type
another_matrix = tf.constant([1.,2.], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [11]:
tensor = tf.constant([[[1,2,3],
                       [1,2,3]],
                      [[1,2,3],
                       [1,2,3]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
# Create tensor with tf.Variable()
changeable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([1,2])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [19]:
# Change one element in the changeable tensor
changeable_tensor[0].assign(5)
# unchangeable_tensor[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 2], dtype=int32)>

In [22]:
# Creating random tensors
random_1 = tf.random.Generator.from_seed(5)
random_1 = tf.random.uniform(shape=(2,2))
random_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.63581395, 0.6244606 ],
       [0.18358326, 0.6250646 ]], dtype=float32)>

In [24]:
random_2 = tf.random.normal(shape=(2,2))
random_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.1865299, -1.0164912],
       [ 0.9371584, -0.3069691]], dtype=float32)>

In [39]:
# shuffle the order of elemnts
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])

# shuffled along the 1st dimension
tf.random.set_seed(5) # global level seed 
tf.random.shuffle(not_shuffled, seed=5) # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [40]:
#other ways to make tensors
tf.ones([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [45]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [47]:
# Turn numpy arrays to tensors
import numpy as np

numpy_array = np.arange(1, 25, dtype = np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [49]:
tensor_array = tf.constant(numpy_array)
tensor_array

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [50]:
tensor_array = tf.constant(numpy_array,shape=(2,3,4))
tensor_array

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>