<a href="https://colab.research.google.com/github/jasonstoy/TensorFlow/blob/main/1.Create%20a%20Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [6]:
# cmd + shift + space: check Fn

In [5]:
# Create tensors with tf.constant
scalar = tf.constant(1) 
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [8]:
# Creat a vector
vector = tf.constant([1,1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [9]:
vector.ndim

1

In [10]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
matrix.ndim

2

In [14]:
# Create another matrix with specified data type
another_matrix = tf.constant([1.,2.], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

In [18]:
tensor = tf.constant([[[1,2,3],
                       [1,2,3]],
                      [[1,2,3],
                       [1,2,3]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [19]:
tensor.ndim

3