<a href="https://colab.research.google.com/github/jasonstoy/TensorFlow/blob/main/2.%20Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

tf.random.set_seed(5)

2.6.0


In [55]:
#get information from tensors
#shape, rank, axis or dimension, size

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [56]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [57]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [58]:
print("data type:", rank_4_tensor.dtype)
print("number of dimensions:", rank_4_tensor.ndim)
print("elements along 0 axis:", rank_4_tensor.shape[0])
print("elements along last axis:", rank_4_tensor.shape[-1])
print("total number of elements in the tensor:", tf.size(rank_4_tensor))

data type: <dtype: 'float32'>
number of dimensions: 4
elements along 0 axis: 2
elements along last axis: 5
total number of elements in the tensor: tf.Tensor(120, shape=(), dtype=int32)


In [59]:
# Index Tensors
# get first 2 tensor for each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [60]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [61]:
# rank 2 tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [62]:
# get the last item of eanch of rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [63]:
# adding extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # [..., tf.newaxis] equal to [:, :, tf.newaxis]
rank_3_tensor

# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [64]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [65]:
# tensor operations
# +, -, *, /

tensor = tf.constant([[1,2],[3,4]])
tensor + 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [66]:
# orginal tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [67]:
# build in
tf.multiply(tensor,10) #use tf operation when use GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [68]:
# matrix multiplication
# inner dimension should match
tensor_2 = tf.constant([[2],[3]])
tf.matmul(tensor, tensor_2)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 8],
       [18]], dtype=int32)>

In [69]:
tensor * tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 9, 12]], dtype=int32)>

In [70]:
# @ is matix multiplication in Python
tensor @ tensor_2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 8],
       [18]], dtype=int32)>

In [71]:
tensor = tf.constant([[1,2],
                      [3,4],
                      [5,6]])

tensor2 = tf.constant([[7,8],
                       [9,10],
                       [11,12]])

tf.matmul(tensor, tf.reshape(tensor2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [72]:
tf.matmul(tensor, tf.transpose(tensor2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [73]:
# dot product (matrix multiplication)
tf.tensordot(tensor, tf.transpose(tensor2),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [74]:
# rehape and transpose are different
tf.transpose(tensor2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [75]:
tf.reshape(tensor2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [76]:
# change data type
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [77]:
# int32 to int16
new_tensor = tf.cast(tensor, dtype=tf.int16)
new_tensor

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

In [78]:
# aggregating tensors

# absolute value
T = tf.constant([-5,-2])
tf.abs(T)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 2], dtype=int32)>

In [81]:
# min, max, sum, mean
random_tensor = tf.constant(np.random.randint(0,100,size=50))
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([98, 29, 75, 86, 14, 51, 22, 53, 18, 33, 14, 27, 64, 20, 15, 88, 89,
       80, 99, 29, 61, 48, 60, 42, 40,  4, 59, 86, 15, 94, 89, 88,  8, 59,
       64, 50, 22, 93, 94, 66, 46, 77, 82, 52, 58, 63, 42, 53, 83, 84])>

In [82]:
# Find the minimum
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [83]:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [84]:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2786>

In [87]:
import tensorflow_probability as tfp
tfp.stats.stddev(tf.cast(random_tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.743135>

In [89]:
tf.math.reduce_std(tf.cast(random_tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.743135>

In [92]:
# find positional min, max
F = tf.random.uniform(shape=[50],seed=5)
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.22574675, 0.19052148, 0.4683671 , 0.20076501, 0.4350201 ,
       0.76375616, 0.40015733, 0.5438293 , 0.0957675 , 0.43651903,
       0.89804673, 0.04670155, 0.36940324, 0.03501081, 0.48912692,
       0.10751057, 0.26041257, 0.90923774, 0.17332578, 0.35813332,
       0.85058165, 0.43108344, 0.24167705, 0.04935944, 0.33212602,
       0.19874728, 0.4658394 , 0.44857216, 0.9579562 , 0.9987308 ,
       0.7118342 , 0.84678376, 0.6411067 , 0.29668045, 0.85039437,
       0.95672166, 0.28903425, 0.06219065, 0.5733595 , 0.09435093,
       0.5614115 , 0.7421849 , 0.0925504 , 0.56545377, 0.695117  ,
       0.0728792 , 0.04827309, 0.38940454, 0.47998583, 0.92448413],
      dtype=float32)>

In [93]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=29>

In [94]:
F[29]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9987308>

In [95]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9987308>

In [97]:
# squeeze a tensor
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.7017075 , 0.04336786, 0.5604572 , 0.12203383, 0.2799585 ,
          0.0750066 , 0.402349  , 0.9894742 , 0.59372437, 0.7514732 ,
          0.05478573, 0.07989085, 0.7620882 , 0.79115105, 0.30476165,
          0.76132965, 0.5997071 , 0.5431193 , 0.88584435, 0.48674047,
          0.01316273, 0.58793426, 0.327574  , 0.23840785, 0.9266187 ,
          0.86423695, 0.1886512 , 0.6405152 , 0.21826982, 0.904871  ,
          0.9731147 , 0.24966395, 0.33211505, 0.37862694, 0.8401406 ,
          0.9709687 , 0.86095977, 0.6963903 , 0.3715824 , 0.6956036 ,
          0.9116014 , 0.32936776, 0.01622629, 0.9951675 , 0.8455043 ,
          0.4008628 , 0.917194  , 0.11467779, 0.8135506 , 0.08010972]]]],
      dtype=float32)>

In [98]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7017075 , 0.04336786, 0.5604572 , 0.12203383, 0.2799585 ,
       0.0750066 , 0.402349  , 0.9894742 , 0.59372437, 0.7514732 ,
       0.05478573, 0.07989085, 0.7620882 , 0.79115105, 0.30476165,
       0.76132965, 0.5997071 , 0.5431193 , 0.88584435, 0.48674047,
       0.01316273, 0.58793426, 0.327574  , 0.23840785, 0.9266187 ,
       0.86423695, 0.1886512 , 0.6405152 , 0.21826982, 0.904871  ,
       0.9731147 , 0.24966395, 0.33211505, 0.37862694, 0.8401406 ,
       0.9709687 , 0.86095977, 0.6963903 , 0.3715824 , 0.6956036 ,
       0.9116014 , 0.32936776, 0.01622629, 0.9951675 , 0.8455043 ,
       0.4008628 , 0.917194  , 0.11467779, 0.8135506 , 0.08010972],
      dtype=float32)>