<a href="https://colab.research.google.com/github/jasonstoy/TensorFlow/blob/main/3.%20Tensor%20Basics%20Contd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.6.0


In [3]:
# One-hot endoing tensors
some_list = [0,1,2,3] #could be red, green, blue, purple

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [4]:
# specify custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value='yes', off_value='no')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

In [5]:
# other operations

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [6]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [7]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [8]:
# tensors and numpy
J = tf.constant(np.array([1,2,3]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [9]:
np.array(J)

array([1, 2, 3])

In [10]:
J.numpy()

array([1, 2, 3])

In [11]:
# different dtype when create tensor
numpy_J = tf.constant(np.array([1.,2.]))
tensor_J = tf.constant([1.,2.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [12]:
# Find access to GPU
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [13]:
!nvidia-smi

Sat Aug 21 20:05:30 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |    222MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------